let exerciseNames = [
    // Barbell Exercises
    "Barbell Bench Press",
    "Barbell Bent Over Rows (Pendlay Rows)",
    "Barbell Bicep Curls",
    "Barbell Deadlifts (Conventional)",
    "Barbell Deadlifts (Romanian)",
    "Barbell Deadlifts (Sumo)",
    "Barbell Front Squats",
    "Barbell Glute Bridges",
    "Barbell Good Mornings",
    "Barbell Hack Squats",
    "Barbell Hip Thrusts",
    "Barbell Incline Bench Press",
    "Barbell Lunges",
    "Barbell Military Press (Overhead Press)",
    "Barbell Romanian Deadlifts",
    "Barbell Shrugs",
    "Barbell Squats (Back Squats)",
    "Barbell Stiff-Legged Deadlifts",
    "Barbell Upright Rows",
    
    // Cable Machine Exercises
    "Cable Bicep Curls",
    "Cable Chest Flyes",
    "Cable Crunches",
    "Cable Face Pulls",
    "Cable Lateral Raises",
    "Cable Leg Kickbacks",
    "Cable Pull-Throughs",
    "Cable Rear Delt Flyes",
    "Cable Rope Hammer Curls",
    "Cable Russian Twists",
    "Cable Seated Rows",
    "Cable Shoulder Press",
    "Cable Tricep Extensions",
    "Cable Woodchoppers",
    
    // Dumbbell Exercises
    "Dumbbell Bench Press",
    "Dumbbell Bicep Curls (Alternating)",
    "Dumbbell Deadlifts",
    "Dumbbell Decline Bench Press",
    "Dumbbell Decline Flyes",
    "Dumbbell Front Raises",
    "Dumbbell Hammer Curls",
    "Dumbbell Incline Bench Press",
    "Dumbbell Incline Curls",
    "Dumbbell Lateral Raises",
    "Dumbbell Lunges",
    "Dumbbell Overhead Press",
    "Dumbbell Pullovers",
    "Dumbbell Renegade Rows",
    "Dumbbell Reverse Lunges",
    "Dumbbell Romanian Deadlifts",
    "Dumbbell Shrugs",
    "Dumbbell Step-Ups",
    "Dumbbell Tricep Extensions",
    "Dumbbell Tricep Kickbacks",
    "Dumbbell Upright Rows",
    
    // Kettlebell Exercises
    "Kettlebell Bent Over Rows",
    "Kettlebell Clean and Press",
    "Kettlebell Goblet Squats",
    "Kettlebell Russian Swings",
    "Kettlebell Turkish Get-Ups",
    
    // Medicine Ball Exercises
    "Medicine Ball Chest Pass",
    "Medicine Ball Russian Twists",
    "Medicine Ball Slams",
    "Medicine Ball Squat Throws",
    
    // Resistance Band Exercises
    "Band Pull-Aparts",
    "Resistance Band Bicep Curls",
    "Resistance Band Face Pulls",
    "Resistance Band Leg Press",
    "Resistance Band Tricep Extensions",
    
    // Barbell Variations
    "Close-Grip Bench Press",
    "Concentration Curls",
    "Diamond Push-Ups",
    "Farmer's Walk",
    "Reverse Grip Bent Over Rows",
    "Sumo Deadlifts",
    "T-Bar Rows",
    "Trap Bar Deadlifts",
    "Wide-Grip Lat Pulldowns",
    
    // Cable Machine Variations
    "High Cable Curls",
    "Low Cable Rows",
    "Single Arm Cable Press",
    "Standing Cable Crunches",
    "Straight Arm Pulldowns",
    
    // Dumbbell Variations
    "Alternating Dumbbell Bench Press",
    "Dumbbell Front Squats",
    "Dumbbell Incline Flyes",
    "Dumbbell Kickbacks",
    "Dumbbell Side Raises",
    "Single Arm Dumbbell Rows",
    "Zercher Squats",
    
    // Smith Machine Exercises
    "Smith Machine Bench Press",
    "Smith Machine Bent Over Rows",
    "Smith Machine Calf Raises",
    "Smith Machine Close-Grip Bench Press",
    "Smith Machine Deadlifts",
    "Smith Machine Front Squats",
    "Smith Machine Glute Bridges",
    "Smith Machine Hack Squats",
    "Smith Machine Hip Thrusts",
    "Smith Machine Incline Bench Press",
    "Smith Machine Leg Press",
    "Smith Machine Lunges",
    "Smith Machine Military Press",
    "Smith Machine Romanian Deadlifts",
    "Smith Machine Shoulder Press",
    "Smith Machine Shrugs",
    "Smith Machine Squats",
    "Smith Machine Stiff-Legged Deadlifts",
    "Smith Machine Upright Rows",
    
    // Additional Weighted Exercises
    "Chest Supported T-Bar Rows",
    "Dumbbell Farmer's Walk",
    "Dumbbell Goblet Lunges",
    "Dumbbell Man Makers",
    "Dumbbell Side Lunges",
    "Landmine Rows",
    "Landmine Squats",
    "Seated Leg Press",
    "Weighted Bulgarian Split Squats",
    "Weighted Chin-Ups",
    "Weighted Dips",
    "Weighted Hyperextensions",
    "Weighted Incline Sit-Ups",
    "Weighted Pistol Squats",
    "Weighted Planks",
    "Weighted Push Press",
    "Weighted Reverse Hyperextensions",
    "Weighted Sled Push/Pull",
    "Weighted Sledgehammer Swings",
    "Weighted Sprints",
    "Weighted Sumo Squats",
    "Weighted Swiss Ball Leg Curls",
    "Weighted Swiss Ball Wall Squats",
    "Weighted Wrist Curls"
]
