//
//  ExerciseNames.swift
//  AthleteIQ
//
//  Created by Mike Iannotti on 3/25/24.
//

import Foundation

let exerciseNames = [
    "Ab Rollouts",
    "Arnold Press",
    "Barbell Bench Press",
    "Barbell Bicep Curls",
    "Barbell Squats (Back Squats)",
    "Bent Over Barbell Rows",
    "Bicycle Crunches",
    "Bulgarian Split Squats",
    "Burpees",
    "Cable Bicep Curls",
    "Cable Chest Flyes",
    "Cable Crunches",
    "Cable Seated Rows",
    "Calf Raises (Seated)",
    "Calf Raises (Standing)",
    "Chin-Ups",
    "Clean and Press",
    "Close-Grip Bench Press",
    "Concentration Curls",
    "Deadlifts (Conventional)",
    "Deadlifts (Romanian)",
    "Deadlifts (Sumo)",
    "Diamond Push-Ups",
    "Dumbbell Bench Press",
    "Dumbbell Front Raises",
    "Dumbbell Hammer Curls",
    "Dumbbell Lateral Raises",
    "Dumbbell Shoulder Press",
    "Glute Bridges",
    "Good Mornings",
    "Hanging Leg Raises",
    "Hyperextensions",
    "Incline Bench Press",
    "Incline Dumbbell Curls",
    "Kickbacks",
    "Kettlebell Swings",
    "Lat Pulldowns",
    "Leg Curls",
    "Leg Extensions",
    "Leg Press",
    "Lunges (Reverse Lunges)",
    "Lunges (Walking Lunges)",
    "Military Press (Overhead Press)",
    "Pec Deck Machine",
    "Planks",
    "Preacher Curls",
    "Pull-Ups",
    "Push-Ups",
    "Rear Deltoid Flyes",
    "Russian Twists",
    "Skull Crushers (Lying Tricep Extensions)",
    "Snatches",
    "T-Bar Rows",
    "Thrusters",
    "Tricep Dips",
    "Tricep Pushdowns",
    "Turkish Get-Ups",
    "Upright Rows",
    "Woodchoppers"
]
